name: Maren
favicon: null
layout_spectrum: 0.7735932262148708
typography_spectrum: 0.033991603180766106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.15642326581291854
  lightness: 0.23280117963440716
  saturation: 0.7803133274428546
  rhythmicContrast: 0.5590797869954258
purpose: []
